[package]
name = "puzzles_crosswise"
version = "0.1.0"
authors = ["Ben Weedon <ben@weedon.email>"]
edition = "2018"

[dependencies]
bincode = "1.2.1"
redis = "0.15.1"
reqwest = { version = "0.10.4", features = ["blocking"] }
rocket = "0.4.4"
serde = { version = "1.0.106", features = ["derive"] }
