[package]
name = "puzzles_crosswise"
version = "0.1.0"
authors = ["Ben Weedon <ben@weedon.email>"]
edition = "2018"

[dependencies]
bincode = "1.1.2"
redis = "0.10.0"
reqwest = "0.9.9"
rocket = "0.4.0"
serde = { version = "1.0.89", features = ["derive"] }
