[package]
name = "puzzles_crosswise"
version = "0.1.0"
authors = ["Ben Weedon <ben@weedon.email>"]
edition = "2018"

[dependencies]
bincode = "1.3.1"
redis = "0.18.0"
reqwest = { version = "0.10.9", features = ["blocking"] }
rocket = "0.4.6"
serde = { version = "1.0.118", features = ["derive"] }
